version: '3'
networks:
  backend:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persons
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    networks:
      - backend

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: go-test
    restart: no
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go
    restart: on-failure
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: persons
    depends_on:
      - postgres
    networks:
      - backend
    ports:
      - "43430:43430"

volumes:
  db-data:
