
services:
  - type: web
    runtime: docker
    name: loyalty
    rootDir: loyalty
    healthCheckPath: /manage/health
    envVars:
      - key: DB_HOST
        value: dpg-ct1kurt2ng1s73e7farg-a
      - key: DB_NAME
        value: main_uo8d
      - key: DB_USER
        value: main_uo8d_user:qwASOBjozdWOki4RaKltjEGHY9aLwnfB
      - key: DB_PASSWORD
        value: ""
      - key: APP_PORT
        value: 8050

databases:
  - name: main
