services:
  - type: web
    plan: free
    name: go-app
    runtime: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      DB_PASSWORD: postgres
      DB_NAME: persons

databases:
  - name: postgres
    diskSizeGB: 1
    databaseName: persons
    user: postgres
    postgresMajorVersion: 16