###
GET 127.0.0.1:8070/hotels

### бронирование
POST 127.0.0.1:8070/reservations
Content-Type: application/json
X-User-Name: Uzername

{
  "paymentUid": "104aef59-61aa-4478-96c3-53d904f57e01",
  "hotelUid": "204aef59-61aa-4478-96c3-53d904f57e20",
  "startDate": "2021-10-08",
  "endDate": "2021-10-11"
}


### бронирования пользователя
GET 127.0.0.1:8070/reservations
X-User-Name: Uzername