-- file: 0000001_create_user_and_db_IGNORE_TEST.sql
CREATE DATABASE persons;
CREATE ROLE program WITH PASSWORD 'test';
GRANT ALL PRIVILEGES ON DATABASE persons TO program;
CREATE SCHEMA public;
GRANT ALL PRIVILEGES ON SCHEMA public TO program;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO program;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO program;
ALTER ROLE program WITH LOGIN;