name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Up Compose (App)
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: app

  local_tests:
    needs: [build]
    name: Testing
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-alpine

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - run: go mod tidy
      - run: go build -o main .

      - run: go test
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: postgres:5432

  deploy:
    needs: [local_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment to render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          wait_deploy: true

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://rsoi-awsy.onrender.com/health
          follow-redirect: false
          max-attempts: 10
          retry-delay: 10s
          retry-all: false

  api_tests:
    needs: [deploy]
    name: Api tests (newman)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: app

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][render] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

  autograding:
    needs: [api_tests]
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"