name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  persons_test:
    name: Persons test
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-alpine

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: go mod tidy
      - run: go build -o main .

      - run: go test
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: postgres:5432

  payment_test:
    name: Payment test
    runs-on: ubuntu-latest
    container:
      image: python:3.12.7-alpine3.20

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: python -m unittest
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: postgres

  loyalty_test:
    name: Loyalty test
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk-jammy

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y maven && mvn dependency:go-offline
      - run: mvn test
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: postgres:5432

  deploy:
    needs: [persons_test, payment_test, loyalty_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment to render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          wait_deploy: true

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://rsoi-awsy.onrender.com/health
          follow-redirect: false
          max-attempts: 10
          retry-delay: 10s
          retry-all: false
